source "https://rubygems.org"

gem "google-showcase", "~> 0.1.0"
gem "minitest", "~> 5.10"

# TODO: remove once gems are published with the annotation classes
gem "googleapis-common-protos-types", :git => "git@github.com:googleapis/common-protos-ruby.git", :branch => "annotations-prerelease"
