/* Copyright 2016 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.api.codegen;

import com.google.api.codegen.advising.Adviser;
import com.google.api.codegen.config.GapicProductConfig;
import com.google.api.codegen.config.PackageMetadataConfig;
import com.google.api.codegen.gapic.GapicGeneratorConfig;
import com.google.api.codegen.gapic.GapicProvider;
import com.google.api.codegen.gapic.GapicProviderFactory;
import com.google.api.codegen.util.ClassInstantiator;
import com.google.api.tools.framework.model.ConfigSource;
import com.google.api.tools.framework.model.Diag;
import com.google.api.tools.framework.model.Model;
import com.google.api.tools.framework.model.SimpleLocation;
import com.google.api.tools.framework.model.stages.Merged;
import com.google.api.tools.framework.tools.ToolDriverBase;
import com.google.api.tools.framework.tools.ToolOptions;
import com.google.api.tools.framework.tools.ToolOptions.Option;
import com.google.api.tools.framework.tools.ToolUtil;
import com.google.common.annotations.VisibleForTesting;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Maps;
import com.google.common.collect.Sets;
import com.google.inject.TypeLiteral;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.Message;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Main class for the code generator. */
public class CodeGeneratorApi extends ToolDriverBase {
  public static final Option<String> OUTPUT_FILE =
      ToolOptions.createOption(
          String.class,
          "output_file",
          "The name of the output file or folder to put generated code.",
          "");

  public static final Option<List<String>> GENERATOR_CONFIG_FILES =
      ToolOptions.createOption(
          new TypeLiteral<List<String>>() {},
          "config_files",
          "The list of YAML configuration files for the code generator.",
          ImmutableList.of());

  public static final Option<String> PACKAGE_CONFIG_FILE =
      ToolOptions.createOption(
          String.class, "package_config", "The package metadata configuration.", "");

  public static final Option<List<String>> ENABLED_ARTIFACTS =
      ToolOptions.createOption(
          new TypeLiteral<List<String>>() {},
          "enabled_artifacts",
          "The artifacts to be generated by the code generator.",
          ImmutableList.of());

  public static final Option<List<String>> ADVICE_SUPPRESSORS =
      ToolOptions.createOption(
          new TypeLiteral<List<String>>() {},
          "supress_warning",
          "Names of adviser rules to suppress warnings for.",
          ImmutableList.of());

  /** Constructs a code generator api based on given options. */
  public CodeGeneratorApi(ToolOptions options) {
    super(options);
  }

  @Override
  public ExtensionRegistry getPlatformExtensions() {
    ExtensionRegistry extensionRegistry = super.getPlatformExtensions();
    return extensionRegistry;
  }

  @Override
  protected void process() throws Exception {

    // Read the YAML config and convert it to proto.
    List<String> configFileNames = options.get(GENERATOR_CONFIG_FILES);
    if (configFileNames.size() == 0) {
      error(String.format("--%s must be provided", GENERATOR_CONFIG_FILES.name()));
      return;
    }

    ConfigSource configSource = loadConfigFromFiles(configFileNames);
    if (configSource == null) {
      return;
    }

    ConfigProto configProto = (ConfigProto) configSource.getConfig();
    if (configProto == null) {
      return;
    }

    model.establishStage(Merged.KEY);

    List<String> adviceSuppressors = options.get(ADVICE_SUPPRESSORS);
    Adviser adviser = new Adviser(adviceSuppressors);
    adviser.advise(model, configProto);

    if (model.getDiagCollector().getErrorCount() > 0) {
      for (Diag diag : model.getDiagCollector().getDiags()) {
        System.err.println(diag.toString());
      }
      return;
    }

    PackageMetadataConfig packageConfig = null;
    if (!Strings.isNullOrEmpty(options.get(PACKAGE_CONFIG_FILE))) {
      String contents =
          new String(
              Files.readAllBytes(Paths.get(options.get(PACKAGE_CONFIG_FILE))),
              StandardCharsets.UTF_8);
      packageConfig = PackageMetadataConfig.createFromString(contents);
    }
    GeneratorProto generator = configProto.getGenerator();
    if (GeneratorProto.getDefaultInstance().equals(generator)) {
      throw new IllegalArgumentException("Language-specific generator config not provided");
    }
    GapicProductConfig productConfig = GapicProductConfig.create(model, configProto);

    if (productConfig == null) {
      return;
    }
    if (generator != null) {
      String factory = generator.getFactory();
      String id = generator.getId();
      Preconditions.checkArgument(!Strings.isNullOrEmpty(factory), "generator.factory is not set");
      Preconditions.checkArgument(!Strings.isNullOrEmpty(id), "generator.id is not set");

      GapicProviderFactory providerFactory = createProviderFactory(model, factory);
      GapicGeneratorConfig generatorConfig =
          GapicGeneratorConfig.newBuilder()
              .id(id)
              .enabledArtifacts(options.get(ENABLED_ARTIFACTS))
              .build();

      String outputPath = options.get(OUTPUT_FILE);
      List<GapicProvider<?>> providers =
          providerFactory.create(model, productConfig, generatorConfig, packageConfig);
      Map<String, Object> outputFiles = Maps.newHashMap();
      Set<String> executables = Sets.newHashSet();
      for (GapicProvider<?> provider : providers) {
        Map<String, ? extends GeneratedResult<?>> providerResult = provider.generate();
        for (Map.Entry<String, ? extends GeneratedResult<?>> entry : providerResult.entrySet()) {
          outputFiles.put(entry.getKey(), entry.getValue().getBody());
          if (entry.getValue().isExecutable()) {
            executables.add(entry.getKey());
          }
        }
      }
      writeCodeGenOutput(outputFiles, outputPath);
      setOutputFilesPermissions(executables, outputPath);
    }
  }

  @VisibleForTesting
  void writeCodeGenOutput(Map<String, ?> outputFiles, String outputPath) throws IOException {
    // TODO: Support zip output.
    if (outputPath.endsWith(".jar")) {
      ToolUtil.writeJar(outputFiles, outputPath);
    } else {
      ToolUtil.writeFiles(outputFiles, outputPath);
    }
  }

  @VisibleForTesting
  void setOutputFilesPermissions(Set<String> executables, String outputPath) {
    if (outputPath.endsWith(".jar")) {
      return;
    }
    for (String executable : executables) {
      File file =
          Strings.isNullOrEmpty(outputPath)
              ? new File(executable)
              : new File(outputPath, executable);
      if (!file.setExecutable(true, false)) {
        warning("Failed to set output file as executable. Probably running on a non-POSIX system.");
      }
    }
  }

  private static GapicProviderFactory createProviderFactory(final Model model, String factory) {
    @SuppressWarnings("unchecked")
    GapicProviderFactory provider =
        ClassInstantiator.createClass(
            factory,
            GapicProviderFactory.class,
            new Class<?>[] {},
            new Object[] {},
            "generator",
            (message, args) ->
                model
                    .getDiagCollector()
                    .addDiag(Diag.error(SimpleLocation.TOPLEVEL, message, args)));
    return provider;
  }

  private ConfigSource loadConfigFromFiles(List<String> configFileNames) {
    List<File> configFiles = pathsToFiles(configFileNames);
    if (model.getDiagCollector().getErrorCount() > 0) {
      return null;
    }
    ImmutableMap<String, Message> supportedConfigTypes =
        ImmutableMap.of(
            ConfigProto.getDescriptor().getFullName(), ConfigProto.getDefaultInstance());
    return MultiYamlReader.read(model.getDiagCollector(), configFiles, supportedConfigTypes);
  }

  private List<File> pathsToFiles(List<String> configFileNames) {
    List<File> files = new ArrayList<>();

    for (String configFileName : configFileNames) {
      File file = model.findDataFile(configFileName);
      if (file == null) {
        error("Cannot find configuration file '%s'.", configFileName);
        continue;
      }
      files.add(file);
    }

    return files;
  }

  private void error(String message, Object... args) {
    model.getDiagCollector().addDiag(Diag.error(SimpleLocation.TOPLEVEL, message, args));
  }

  private void warning(String message, Object... args) {
    model.getDiagCollector().addDiag(Diag.warning(SimpleLocation.TOPLEVEL, message, args));
  }
}
